# Generated by Django 6.0.1 on 2026-02-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_pedido_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="mensagem",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aceito", "Aceito"),
                    ("em_andamento", "Em andamento"),
                    ("finalizado", "Finalizado"),
                    ("recusado", "Recusado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
