# Generated by Django 6.0.2 on 2026-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestadorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
