# Generated by Django 6.0.3 on 2026-03-07 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prestadorprofile_latitude_prestadorprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorprofile',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestadorprofile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_prestador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='accounts.prestadorprofile')),
            ],
        ),
    ]
