# Generated by Django 6.0.3 on 2026-03-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_prestadorprofile_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestadorprofile",
            name="categoria",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="prestadorprofile",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="prestadorprofile",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="prestadorprofile",
            name="nome_empresa",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ClienteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="clientes/"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
