# Generated by Django 6.0.3 on 2026-03-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_prestadorprofile_categoria_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClienteProfile",
        ),
    ]
