# Generated by Django 6.0.3 on 2026-03-14 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_clienteprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestadorprofile",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="perfil/"),
        ),
        migrations.CreateModel(
            name="ClienteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="perfil/")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
